site_name: "emojifont"
site_url: https://guangchuangyu.github.io/emojifont
site_author: Guangchuang Yu
repo_url: https://github.com/GuangchuangYu/emojifont
site_dir: ../docs
google_analytics: ['UA-77901140-1', 'guangchuangyu.github.io']
pages:
- Home: index.md
- Blog:
  - use emoji font in R: emojifontR.md
  - font awesome supported in emojifont: fontawesome.md
- Gallery: gallery.md
- My Software:
  - ChIPseeker: ChIPseeker.md
  - clusterProfiler: clusterProfiler.md
  - DOSE: DOSE.md
  - emojifont: emojifont.md
  - ggtree: ggtree.md
  - GOSemSim: GOSemSim.md
  - meshes: meshes.md
  - ReactomePA: ReactomePA.md
  - treeio: treeio.md

copyright: Copyright &copy; 2016 <a href="https://guangchuangyu.github.io">Guangchuang Yu</a>.<div style="width:250px;margin:auto;"><script type="text/javascript" src="//rf.revolvermaps.com/0/0/7.js?i=5qpvv5zz7fp&amp;m=0&amp;c=ff0000&amp;cr1=ffffff&amp;sx=0" async="async"></script></div>
